kind: pipeline
name: default

steps:

- name: docker
  image: plugins/docker
  settings:
    username: drone
    password:
      from_secret: docker_password
    repo: registry.webix.io/${DRONE_REPO_NAME}
    tags:
      - ${DRONE_BRANCH}
    registry: registry.webix.io

- name: deploy
  image: registry.webix.io/citools:1.0
  environment:
    DOCS_RESTART_DOCKER:
      from_secret: docs_restart_docker
  commands:
    - curl -s "https://docs.dhtmlx.com/hooks/restart-docker?project=backend-project-management&token=$DOCS_RESTART_DOCKER"
  when:
    branch:
      include:
        - master

trigger:
  branch:
    exclude:
      - temp/*